---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: demo-secret
  namespace: default
data:
  username: ZGVtbw== # demo
  password: ZGVtbw==

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-s3-creds
  namespace: default
data:
  ACCESS_KEY_ID: $ACCESS_KEY_ID_B64
  ACCESS_SECRET_KEY: $ACCESS_SECRET_KEY_B64
  REGION: $REGION_B64
